apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sampleapp2
  name: sampleapp2
spec:
  ports:
    - name: sampleapp-svc
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: sampleapp2
  type: ClusterIP
status:
  loadBalancer: {}
