apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
spec:
  destination:
    name: ""
    namespace: sample
    server: "https://kubernetes.default.svc"
  source:
    path: ./sampleapp/
    repoURL: "https://github.com/kgopi1/argocd"
    targetRevision: itr1
  sources: []
  project: default        sampleapp/
        sampleapp2/

no changes added to commit
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
