apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app2
spec:
  destination:
    name: ""
    namespace: sampleapp2
    server: "https://kubernetes.default.svc"
  source:
    path: ./sample-app2/
    repoURL: "https://github.com/kgopi1/argocd"
    targetRevision: itr1
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
